/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.dbproject;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Date;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abd Alrahman
 */
public class Achievementformanager extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private int selectedRowId = -1;
    /**
     * Creates new form Achievementformanager
     */
    public Achievementformanager() {
         initComponents();
    setupTableModel();
    setupRowSelectionListener();
    
    // Set current date as default for new entries
    jTextField3.setText(getCurrentTimestampString());
    
    // Load initial data
    loadAchievements();
    }
    private void setupTableModel() {
    // Define column names
    String[] columnNames = {"ID", "Title", "Description", "Date"};
    
    // Create model with columns
    tableModel = new DefaultTableModel(columnNames, 0) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (columnIndex == 0) return Integer.class;
            if (columnIndex == 3) return java.sql.Timestamp.class;
            return String.class;
        }
        
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Make all cells non-editable
        }
    };
    
    // Set the model to the table
    achievementtable.setModel(tableModel);
    
    // Optional: Hide the ID column if needed
    achievementtable.getColumnModel().getColumn(0).setMinWidth(50);
    achievementtable.getColumnModel().getColumn(0).setPreferredWidth(50);
    
    // Debug
    System.out.println("Table model initialized with columns: " + 
                       String.join(", ", columnNames));
}
    private String getCurrentTimestampString() {
    java.sql.Timestamp timestamp = new java.sql.Timestamp(System.currentTimeMillis());
    java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    return dateFormat.format(timestamp);
}
    private void setupRowSelectionListener() {
    // Create a mouse listener directly without casting
    achievementtable.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            int selectedRow = achievementtable.getSelectedRow();
            if (selectedRow != -1) {
                try {
                    // Use full qualification for all types
                    selectedRowId = (int) tableModel.getValueAt(selectedRow, 0);
                    jTextField1.setText(tableModel.getValueAt(selectedRow, 1).toString()); // Title
                    jTextField2.setText(tableModel.getValueAt(selectedRow, 2).toString()); // Description
                    
                    // Format the date for display
                    java.sql.Timestamp timestamp = (java.sql.Timestamp) tableModel.getValueAt(selectedRow, 3);
                    java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    jTextField3.setText(dateFormat.format(timestamp));
                } catch (Exception ex) {
                    System.err.println("Error selecting row: " + ex.getMessage());
                    ex.printStackTrace();
                }
            }
        }
    });
}
    private void loadAchievements() {
        Services.loadAchievementsToTable(tableModel);
    }
    private void clearFields() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }
     private Timestamp getCurrentTimestamp() {
        return new Timestamp(System.currentTimeMillis());
    }
     private boolean isValidDateFormat(String dateStr) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        dateFormat.setLenient(false);
        try {
            dateFormat.parse(dateStr);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        achievementtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 245, 220));

        achievementtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Discription", "Date"
            }
        ));
        jScrollPane1.setViewportView(achievementtable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Title:");

        jTextField1.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Discription:");

        jTextField2.setText("jTextField2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Date:");

        jTextField3.setText("jTextField3");

        jButton1.setBackground(new java.awt.Color(95, 99, 104));
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(95, 99, 104));
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Update selected");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(95, 99, 104));
        jButton3.setForeground(new java.awt.Color(242, 242, 242));
        jButton3.setText("Delete selected");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField3))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String title = jTextField1.getText().trim();
    String description = jTextField2.getText().trim();
    String dateStr = jTextField3.getText().trim();
    
    if (title.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Title cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // Parse the date string to a timestamp
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        java.util.Date parsedDate = dateFormat.parse(dateStr);
        // Properly convert util.Date to sql.Timestamp
        java.sql.Timestamp timestamp = new java.sql.Timestamp(parsedDate.getTime());
        
        boolean success = Services.addAchievement(title, description, timestamp);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Achievement added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
            loadAchievements(); // Refresh table
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add achievement", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Invalid date format. Use yyyy-MM-dd HH:mm:ss", "Validation Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (selectedRowId == -1) {
        JOptionPane.showMessageDialog(this, "Please select an achievement first", "Selection Required", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String title = jTextField1.getText().trim();
    String description = jTextField2.getText().trim();
    String dateStr = jTextField3.getText().trim();
    
    if (title.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Title cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // Parse the date string to a timestamp - remove the unnecessary casting
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        java.util.Date parsedDate = dateFormat.parse(dateStr);
        java.sql.Timestamp timestamp = new java.sql.Timestamp(parsedDate.getTime());
        
        // Debug information
        System.out.println("Updating achievement ID: " + selectedRowId);
        System.out.println("Title: " + title);
        System.out.println("Description: " + description);
        System.out.println("Date: " + timestamp);
        
        boolean success = Services.updateAchievement(selectedRowId, title, description, timestamp);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Achievement updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadAchievements(); // Refresh table
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update achievement", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Invalid date format. Use yyyy-MM-dd HH:mm:ss", "Validation Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Print stack trace for debugging
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if (selectedRowId == -1) {
            JOptionPane.showMessageDialog(this, "Please select an achievement first", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this achievement?", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = Services.deleteAchievement(selectedRowId);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Achievement deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearFields();
                loadAchievements(); // Refresh table
                selectedRowId = -1; // Reset selection
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete achievement", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable achievementtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
