/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.dbproject;
   
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abd Alrahman
 */
public class Achievement extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private Services services;
    /**
     * Creates new form Achievement
     */
    public Achievement() {
        initComponents();
        services = new Services();
        
        // Get the table model from your existing table
        tableModel = (DefaultTableModel) achievementtable.getModel();
        
        // Load data from database
        loadData();
    }
    public void refreshData() {
        loadData();
    }
    
    public void loadData() {
        // Clear existing data
        tableModel.setRowCount(0);
        
        try {
            // Get achievements from the database
            List<Achievementclass> achievements = services.getAchievements();
            
            // Add achievements to the table
            for (Achievementclass achievement : achievements) {
                Object[] rowData = {
                    achievement.getTitle(),
                    achievement.getDescription(),
                    achievement.getDate()
                };
                
                tableModel.addRow(rowData);
            }
        } catch (Exception e) {
            System.err.println("Error loading achievements: " + e.getMessage());
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        achievementtable = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 245, 220));

        achievementtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Discription", "Date"
            }
        ));
        jScrollPane1.setViewportView(achievementtable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable achievementtable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
