/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.dbproject;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.math.BigDecimal;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Abd Alrahman
 */
public class contractformanager extends javax.swing.JPanel {
    private int selectedContractId = -1;
    private Services services;
    /**
     * Creates new form contractformanager
     */
    public contractformanager() {
        initComponents();
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
    public void itemStateChanged(java.awt.event.ItemEvent evt) {
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedUser = (String) jComboBox1.getSelectedItem();
            loadContractForUser(selectedUser);
        }
    }
});
        services.loadUsersToComboBox(jComboBox1);
        services = new Services();
        setupEventListeners();
        loadUsersToComboBox();
    }
    
    
    private void setupEventListeners() {
        // Setup user selection change listener
        jComboBox1.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedUser = (String) jComboBox1.getSelectedItem();
                    loadContractForUser(selectedUser);
                }
            }
        });
    }
    private void loadUsersToComboBox() {
        Services.loadUsersToComboBox(jComboBox1);
        
        // Load contract for initially selected user if any
        if (jComboBox1.getItemCount() > 0) {
            String initialUser = (String) jComboBox1.getSelectedItem();
            loadContractForUser(initialUser);
        } else {
            clearFields();
        }
    }
    private void loadContractForUser(String userName) {
        int userId = services.getUserIdByName(userName);
        
        if (userId != -1) {
            Map<String, Object> contract = services.getContractByUserId(userId);
            
            if (!contract.isEmpty()) {
                // User has a contract, display its details
                selectedContractId = (int) contract.get("contract_id");
                
                Date startDate = (Date) contract.get("start_date");
                Date endDate = (Date) contract.get("end_date");
                BigDecimal salary = (BigDecimal) contract.get("salary");
                
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                
                jTextField1.setText(startDate != null ? dateFormat.format(startDate) : "");
                jTextField2.setText(endDate != null ? dateFormat.format(endDate) : "");
                jTextField3.setText(salary != null ? salary.toString() : "");
                
                // Enable edit and delete buttons
//                jButton2.setEnabled(true);
//                jButton3.setEnabled(true);
            } else {
                // User doesn't have a contract
                selectedContractId = -1;
                clearFields();
                
                // Disable edit and delete buttons
//                jButton2.setEnabled(false);
//                jButton3.setEnabled(false);
            }
        } else {
            selectedContractId = -1;
            clearFields();
            
            // Disable edit and delete buttons
//            jButton2.setEnabled(false);
//            jButton3.setEnabled(false);
        }
    }
    
    private void clearFields() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 245, 220));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Select User:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Start Date:");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("End Date:");

        jTextField2.setText("jTextField2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Salary:");

        jTextField3.setText("jTextField3");

        jButton1.setBackground(new java.awt.Color(95, 99, 104));
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(95, 99, 104));
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Delete Selected");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(95, 99, 104));
        jButton3.setForeground(new java.awt.Color(242, 242, 242));
        jButton3.setText("Edit Selected");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selectedUser = (String) jComboBox1.getSelectedItem();
        if (selectedUser == null) {
            JOptionPane.showMessageDialog(this, "Please select a user", "User Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int userId = services.getUserIdByName(selectedUser);
        if (userId == -1) {
            JOptionPane.showMessageDialog(this, "Invalid user selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if user already has a contract
        if (services.userHasContract(userId)) {
            JOptionPane.showMessageDialog(this, "This user already has a contract. Please use 'Edit' instead.", 
                    "Contract Exists", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String startDateStr = jTextField1.getText().trim();
        String endDateStr = jTextField2.getText().trim();
        String salaryStr = jTextField3.getText().trim();
        
        // Validate input
        if (startDateStr.isEmpty() || endDateStr.isEmpty() || salaryStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Parse date strings to SQL Date objects
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            
            java.util.Date parsedStartDate = dateFormat.parse(startDateStr);
            java.sql.Date sqlStartDate = new java.sql.Date(parsedStartDate.getTime());
            
            java.util.Date parsedEndDate = dateFormat.parse(endDateStr);
            java.sql.Date sqlEndDate = new java.sql.Date(parsedEndDate.getTime());
            
            // Parse salary
            BigDecimal salary = new BigDecimal(salaryStr);
            
            // Validate end date is after start date
            if (sqlEndDate.before(sqlStartDate)) {
                JOptionPane.showMessageDialog(this, "End date must be after start date", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Add contract to database
            boolean success = services.addContract(userId, sqlStartDate, sqlEndDate, salary);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Contract added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadContractForUser(selectedUser); // Refresh the contract display
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add contract", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Use yyyy-MM-dd", "Validation Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid salary format. Please enter a valid number", "Validation Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (selectedContractId == -1) {
            JOptionPane.showMessageDialog(this, "No contract selected", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String startDateStr = jTextField1.getText().trim();
        String endDateStr = jTextField2.getText().trim();
        String salaryStr = jTextField3.getText().trim();
        
        // Validate input
        if (startDateStr.isEmpty() || endDateStr.isEmpty() || salaryStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Parse date strings to SQL Date objects
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            
            java.util.Date parsedStartDate = dateFormat.parse(startDateStr);
            java.sql.Date sqlStartDate = new java.sql.Date(parsedStartDate.getTime());
            
            java.util.Date parsedEndDate = dateFormat.parse(endDateStr);
            java.sql.Date sqlEndDate = new java.sql.Date(parsedEndDate.getTime());
            
            // Parse salary
            BigDecimal salary = new BigDecimal(salaryStr);
            
            // Validate end date is after start date
            if (sqlEndDate.before(sqlStartDate)) {
                JOptionPane.showMessageDialog(this, "End date must be after start date", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Update contract in database
            boolean success = services.updateContract(selectedContractId, sqlStartDate, sqlEndDate, salary);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Contract updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                String selectedUser = (String) jComboBox1.getSelectedItem();
                loadContractForUser(selectedUser); // Refresh the contract display
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update contract", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Use yyyy-MM-dd", "Validation Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid salary format. Please enter a valid number", "Validation Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (selectedContractId == -1) {
            JOptionPane.showMessageDialog(this, "No contract selected", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this contract?", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = services.deleteContract(selectedContractId);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Contract deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearFields();
                selectedContractId = -1;
//                jButton2.setEnabled(false);
//                jButton3.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete contract", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
