/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.dbproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Abd Alrahman
 */
public class playerinfo extends javax.swing.JPanel {

    private Services services;
    private Player currentPlayer;
    private String loggeninusername;
    private int playerId; 
    
    public playerinfo(String username2) {
        initComponents();
        this.loggeninusername = username2;
        this.services = new Services();
        
        // Load and display player data
       loadPlayerData();
    }
     public void loadPlayerData() {
        // Get player data from the service
        currentPlayer = services.getPlayerByUsername(loggeninusername);
        
        // Display data in the text fields
        usernamevar.setText(currentPlayer.getUsername());
        agevar.setText(String.valueOf(currentPlayer.getAge()));
        healthstatusvar.setText(currentPlayer.getHealthStatus());
        positionvar.setText(currentPlayer.getPosition());
        nationalityvar.setText(currentPlayer.getNationality());
        jersaynumbervar.setText(String.valueOf(currentPlayer.getJerseyNumber()));
                
        healthstatusvar.setEditable(false);
        jersaynumbervar.setEditable(false);
        positionvar.setEditable(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountdetailspanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernamevar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        agevar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        healthstatusvar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        positionvar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nationalityvar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jersaynumbervar = new javax.swing.JTextField();
        editdetails = new javax.swing.JButton();

        accountdetailspanel.setBackground(new java.awt.Color(245, 245, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Username:");

        usernamevar.setText("Dummy name");
        usernamevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamevarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Age:");

        agevar.setText("jTextField5");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Healthstatus:");

        healthstatusvar.setText("jTextField6");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Position:");

        positionvar.setText("jTextField7");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Nationality:");

        nationalityvar.setText("jTextField8");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Jersey number:");

        jersaynumbervar.setText("jTextField9");

        editdetails.setBackground(new java.awt.Color(95, 99, 104));
        editdetails.setForeground(new java.awt.Color(242, 242, 242));
        editdetails.setText("Edit Details");
        editdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountdetailspanelLayout = new javax.swing.GroupLayout(accountdetailspanel);
        accountdetailspanel.setLayout(accountdetailspanelLayout);
        accountdetailspanelLayout.setHorizontalGroup(
            accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountdetailspanelLayout.createSequentialGroup()
                .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountdetailspanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernamevar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(healthstatusvar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(agevar)
                                .addComponent(positionvar)
                                .addComponent(nationalityvar)
                                .addComponent(jersaynumbervar))))
                    .addGroup(accountdetailspanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(editdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        accountdetailspanelLayout.setVerticalGroup(
            accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountdetailspanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamevar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(agevar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(healthstatusvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(positionvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(nationalityvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jersaynumbervar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(editdetails)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(accountdetailspanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(accountdetailspanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernamevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamevarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamevarActionPerformed

    private void editdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdetailsActionPerformed

        // Update player object with values from text fields
        currentPlayer.setAge(Integer.parseInt(agevar.getText()));
        currentPlayer.setHealthStatus(healthstatusvar.getText());
        currentPlayer.setPosition(positionvar.getText());
        currentPlayer.setNationality(nationalityvar.getText());
        currentPlayer.setJerseyNumber(Integer.parseInt(jersaynumbervar.getText()));

        // Save to database using service
        boolean success = services.updatePlayerInfo(currentPlayer);

        JOptionPane.showMessageDialog(this, "Player details updated successfully!");

        // Disable editing
        agevar.setEditable(false);
        healthstatusvar.setEditable(false);
        positionvar.setEditable(false);
        nationalityvar.setEditable(false);
        jersaynumbervar.setEditable(false);

        // Restore button text and action
        editdetails.setText("Edit Details");

    }//GEN-LAST:event_editdetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountdetailspanel;
    private javax.swing.JTextField agevar;
    private javax.swing.JButton editdetails;
    private javax.swing.JTextField healthstatusvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jersaynumbervar;
    private javax.swing.JTextField nationalityvar;
    private javax.swing.JTextField positionvar;
    private javax.swing.JTextField usernamevar;
    // End of variables declaration//GEN-END:variables
}
