/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.dbproject;

import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.export.*;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
/**
 *
 * @author Abd Alrahman
 */
public class Reports extends javax.swing.JPanel {

    private static final String DB_URL = "jdbc:postgresql://localhost:5432/postgres";
    private static final String DB_USER = "abdalrahman";
    private static final String DB_PASSWORD = "Abood-2004!";
    
    // Report file paths - UPDATE TO YOUR ACTUAL PATH
    private static final String REPORTS_PATH = "src/reports/";
    public Reports() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 245, 220));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Staff Directory & Organizational Report:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Player Health Report:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Contract Summary Report:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tournament & Games Management Report:");

        jButton1.setBackground(new java.awt.Color(95, 99, 104));
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Make Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(95, 99, 104));
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Make Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(95, 99, 104));
        jButton3.setForeground(new java.awt.Color(242, 242, 242));
        jButton3.setText("Make Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(95, 99, 104));
        jButton4.setForeground(new java.awt.Color(242, 242, 242));
        jButton4.setText("Make Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton4))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con;
       InputStream input;
       JasperDesign jd;
       JasperReport jr;
       JasperPrint jp;
       OutputStream output;
       
       try{
           DriverManager.deregisterDriver(new org.postgresql.Driver());
           con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","abdalrahman","Abood-2004!");
           input = new FileInputStream (new File ("Healthtest.jrxml"));
           jd=JRXmlLoader.load(input);
           jr=JasperCompileManager.compileReport(jd);
           jp=JasperFillManager.fillReport(jr,null, con);
           output = new FileOutputStream(new File("Health.pdf"));
           JasperExportManager.exportReportToPdfStream(jp, output);
           output.close();
           input.close();
           con.close();
           
           
           
           
       }catch (Exception ex){
           JOptionPane.showMessageDialog(null, ex.toString());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Connection con;
       InputStream input;
       JasperDesign jd;
       JasperReport jr;
       JasperPrint jp;
       OutputStream output;
       
       try{
           DriverManager.deregisterDriver(new org.postgresql.Driver());
           con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","abdalrahman","Abood-2004!");
           input = new FileInputStream (new File ("stafftest.jrxml"));
           jd=JRXmlLoader.load(input);
           jr=JasperCompileManager.compileReport(jd);
           jp=JasperFillManager.fillReport(jr,null, con);
           output = new FileOutputStream(new File("Staff.pdf"));
           JasperExportManager.exportReportToPdfStream(jp, output);
           output.close();
           input.close();
           con.close();
           
           
           
           
       }catch (Exception ex){
           JOptionPane.showMessageDialog(null, ex.toString());
       }
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Connection con;
       InputStream input;
       JasperDesign jd;
       JasperReport jr;
       JasperPrint jp;
       OutputStream output;
       
       try{
           DriverManager.deregisterDriver(new org.postgresql.Driver());
           con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","abdalrahman","Abood-2004!");
           input = new FileInputStream (new File ("Gamestest.jrxml"));
           jd=JRXmlLoader.load(input);
           jr=JasperCompileManager.compileReport(jd);
           jp=JasperFillManager.fillReport(jr,null, con);
           output = new FileOutputStream(new File("Games.pdf"));
           JasperExportManager.exportReportToPdfStream(jp, output);
           output.close();
           input.close();
           con.close();
           
           
           
           
       }catch (Exception ex){
           JOptionPane.showMessageDialog(null, ex.toString());
       }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Connection con;
       InputStream input;
       JasperDesign jd;
       JasperReport jr;
       JasperPrint jp;
       OutputStream output;
       
       try{
           DriverManager.deregisterDriver(new org.postgresql.Driver());
           con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","abdalrahman","Abood-2004!");
           input = new FileInputStream (new File ("contracttest.jrxml"));
           jd=JRXmlLoader.load(input);
           jr=JasperCompileManager.compileReport(jd);
           jp=JasperFillManager.fillReport(jr,null, con);
           output = new FileOutputStream(new File("contract.pdf"));
           JasperExportManager.exportReportToPdfStream(jp, output);
           output.close();
           input.close();
           con.close();
           
           
           
           
       }catch (Exception ex){
           JOptionPane.showMessageDialog(null, ex.toString());
       }       
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
