/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.dbproject;
    
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abd Alrahman
 */
public class tournaments extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private Services services;
    /**
     * Creates new form tournaments
     */
    public tournaments() {
         initComponents();
        
        // Initialize services
        services = new Services();
        
        // Get the table model from your existing table
        tableModel = (DefaultTableModel) tournamentstable.getModel();
        
        // Load data from database
       loadData();
    }
        public void refreshData() {
        loadData();
    }
    
    public void loadData() {
        // Clear existing data
        tableModel.setRowCount(0);
        
        try {
            // Get tournaments from the database
            List<Tournament> tournaments = services.getTournaments();
            
            // Add tournaments to the table
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            
            for (Tournament tournament : tournaments) {
                String startDate = (tournament.getStartDate() != null) ? 
                    dateFormat.format(tournament.getStartDate()) : "";
                String endDate = (tournament.getEndDate() != null) ? 
                    dateFormat.format(tournament.getEndDate()) : "";
                    
                Object[] rowData = {
                    tournament.getTournamentName(),
                    startDate,
                    endDate,
                    tournament.getLocation(),
                    tournament.getStatus()
                };
                
                tableModel.addRow(rowData);
            }
        } catch (Exception e) {
            System.err.println("Error loading tournaments: " + e.getMessage());
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tournamentstable = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 245, 220));

        tournamentstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Start Date", "End Date", "Location", "Status"
            }
        ));
        jScrollPane1.setViewportView(tournamentstable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tournamentstable;
    // End of variables declaration//GEN-END:variables
}
