/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.dbproject;

import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abd Alrahman
 */
public class TrainingPanel extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private Services services;
    /**
     * Creates new form TrainingPanel
     */
    public TrainingPanel() {
        initComponents();
        services = new Services();
        
        // Get the table model from your existing table
        tableModel = (DefaultTableModel) Sessiontable.getModel();
        
        // Load data from database
        loadData();
    }
    public void refreshData() {
        loadData();
    }
    
    public void loadData() {
        // Clear existing data
        tableModel.setRowCount(0);
        
        try {
            // Get training sessions from the database
            List<TrainingSession> sessions = services.getTrainingSessions();
            
            // Add sessions to the table
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
            
            for (TrainingSession session : sessions) {
                String formattedDate = (session.getSessionDate() != null) ? 
                    dateFormat.format(session.getSessionDate()) : "";
                    
                Object[] rowData = {
                    session.getSessionType(),
                    formattedDate
                };
                
                tableModel.addRow(rowData);
            }
        } catch (Exception e) {
            System.err.println("Error loading training sessions: " + e.getMessage());
            e.printStackTrace();
        }
    }//hello

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Sessiontable = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 245, 220));

        Sessiontable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Session Type", "Session Date"
            }
        ));
        jScrollPane1.setViewportView(Sessiontable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Sessiontable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
